# Generated by Django 5.0.6 on 2024-05-19 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parvoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(height_field=300, upload_to='air_imgae/', width_field=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('destination', models.IntegerField()),
                ('view', models.CharField(max_length=1000, null=True)),
                ('image', models.ImageField(null=True, upload_to='service_image/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour', to='blog.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Yunalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avia', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image_p', models.ImageField(null=True, upload_to='pathes_image/')),
                ('air', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air', to='blog.parvoz')),
            ],
        ),
    ]
