# Generated by Django 5.0.6 on 2024-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parvoz',
            name='image',
            field=models.ImageField(null=True, upload_to='air_imgae/'),
        ),
    ]
